// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class deployed_db_edit1_user : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(deployed_db_edit1_user));
        
        string IMigrationMetadata.Id
        {
            get { return "201905012326062_deployed_db_edit1_user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
